name: s_store
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.3.2
  get: ^4.7.2
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/images/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/sent_email/
    - assets/images/banners/
    - assets/images/products/ 
    - assets/images/profile/
    


  fonts:
    - family: pop
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: rob
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: urb
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
